import { describe, it, expect } from 'vitest'
import { readFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, resolve } from 'node:path'
import { analyze } from '../src/analyze.js'
import { rulesDocument } from '../scripts/update-conformance.mjs'
import { RULES_VERSION } from '../src/compliance/index.js'

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const readJson = (rel) => JSON.parse(readFileSync(resolve(root, rel), 'utf8'))

const DEMO_FILES = ['example.json', 'example-vu.json']

// The repository ships two artifacts for reimplementations in other languages:
// src/compliance/rules.json (the numbers) and test/conformance/expected-*.json
// (the output of analyze() over the bundled demo inputs). Both are generated by
// `npm run conformance:update`. These tests fail when they drift from the code,
// so a port that validates against them is validating against the real engine.
describe('conformance artifacts', () => {
  it('rules.json matches rules.js', () => {
    expect(readJson('src/compliance/rules.json')).toEqual(rulesDocument())
  })

  it('rules.json carries the current rule-set version', () => {
    expect(readJson('src/compliance/rules.json').rulesVersion).toBe(RULES_VERSION)
  })

  for (const name of DEMO_FILES) {
    it(`expected-${name} matches analyze() output`, () => {
      const input = readJson(`public/${name}`)
      expect(analyze(input)).toEqual(readJson(`test/conformance/expected-${name}`))
    })
  }

  // A port is checked by diffing whole reports, so the report has to be a
  // function of the input alone - no clock, no locale, no iteration order.
  it('analyze() is deterministic across repeated runs', () => {
    const input = readJson('public/example.json')
    expect(analyze(input)).toEqual(analyze(input))
  })
})
